### ISSUE TITLE
Intelligently select alliances

### ISSUE THREAD

**Issue by blake1029384756** [SUPERCILEX/Robot-Scouter#110]
I dont know if this would be done in the spreadsheet or the app but the user would give the system criteria they want on their alliance like gears in teleop, gear in auto, climbing, and shooting. The system would then intelligently form the best alliance possible. Throughout alliance selections the user would eliminate teams already chosen and the best alliance would then be updated with the remaining teams. 

This all sounds fine and dandy in theory and should work with pure data. Just a thought I had. @SUPERCILEX Thanks again for all the work you have done!

**Comment by vannaka** [comment]
@blake1029384756  This would probably be a 3.0 update.

Would this be meant to replace exporting the data to a spreadsheet? It might not be worth trying to display this data on a phone screen. Excel is much more suited for displaying and manipulating the data.

This feature would need to use the scout templates and let you sort the data in a hierarchical way. i.e first by climbing%, then by avg delivered gears, and then by avg dropped gears, etc. Again, excel is already really good at this. Why should it be a feature of this app?

**Comment by SUPERCILEX** [comment]
@blake1029384756 Oh no... I knew someone would submit an issue like this! 😢

Sorry for that reaction! 😄 Basically, this was my original idea for RS before I started doing the spreadsheet exporting stuff. The plan was to do some insanely awesome machine learning stuff and have, like, the best data analysis app ever, but of course that didn't happen. I started thinking about it and looking into stuff like that and then my brain melted and I decided to not do any data analysis in Robot Scouter and instead let tools like excel do that for me. I think that was the right choice because the point of Robot Scouter is really just to help teams have the most effective and efficient scouting solution possible, hence issues like #55.

However, back when I was looking into that, I didn't even really know Java that well so my brain was already kinda dying trying to learn Android. Since I'm more knowledgable about the whole Android thing now, I'll keep this issue open and consider revisiting it at some later time, probably `v3.0`.

**Comment by SUPERCILEX** [comment]
@vannaka Haha, you're thinking the same stuff as me. 😄 Yeah, my reasoning was also that Excel is better, but I think @blake1029384756's point is to have some screen that doesn't necessarily display data, but instead just tells you what the best alliances for you would be with a brief reasoning. My thoughts were that the feature would be for rookie teams or teams that don't want to spend a lot of time looking for the best alliance. It could be a way of easily filtering out improbably teams.

**Comment by vannaka** [comment]
@SUPERCILEX Ok, new idea. How about we have a lower cutoff that we can set for any field. If a certain teams average for that field falls bellow the cutoff, they don't get exported. We could even set multiple cutoffs. Of course, we could have two options, one to export the raw data and one to export the filtered data.

**Comment by SUPERCILEX** [comment]
@vannaka Oh, that sounds really interesting! I'm not sure if it's possible right now, but with enough thought and effort I think it could get done.

**Comment by blake1029384756** [comment]
@SUPERCILEX, @vannaka Yea I see why this isnt needed now. How about it would just rank teams by the users criteria and then help keep track of who has been selected or not. This past weekend the team I mentor was an alliance captain and screwed up selections because they didnt know who was taken or not.

**Comment by vannaka** [comment]
@blake1029384756 Ya, that sounds good. How about you create an issue for that idea and close this issue.

**Comment by SUPERCILEX** [comment]
I've been thinking about the Robot Scouter roadmap and I'm seeing the focus really being on the actual scouting and making all of that smarter. With the addition of [multiple templates](https://github.com/SUPERCILEX/Robot-Scouter/issues/82), [Auto Scout™️ 😄](https://github.com/SUPERCILEX/Robot-Scouter/issues/55), a [permission model](https://github.com/SUPERCILEX/Robot-Scouter/issues/144), and support for making scouting data [publicly accessible](https://github.com/SUPERCILEX/Robot-Scouter/issues/145), I've got a lot on my plate and I think data analysis will be the last thing I do.

So for now, I'm going to close this issue. 😊
