### ISSUE TITLE
Rework spinner item editing experience

### ISSUE THREAD

**Issue by blake1029384756** [SUPERCILEX/Robot-Scouter#165]
### @SUPERCILEX here

Mock:
![img_20171108_002139 1](https://user-images.githubusercontent.com/9490724/32538519-1dfafb1e-c41b-11e7-94ea-fd9c64bbec26.jpg)

### Original post

Log
[robot.txt](https://github.com/SUPERCILEX/Robot-Scouter/files/1331483/robot.txt)

Robot Scouter version: 1.1.2.1
- Android OS version: 25
- User id: wQPZykRqf9MmbHjgXuflEJ3q0G42

I am unable to edit the item selector metric. The app crashes when I tap the edit items button.

**Comment by SUPERCILEX** [comment]
@blake1029384756 That would be because I do this:
```kt
throw NotImplementedError("An operation is not implemented: Rewrite spinner item stuff")
```
😀

Do you need to use RS for an event? If so, I could manually enter data into the database, but for now that's on my TODO list. The dialog was gross so I'm trying to redesign that editing experience to be inlined into the metric i.e. you would press a `+` button in the metric and a new inlined item would show up below. Still trying to figure out the UI and code, but it'll get done either way before 2.0 is out.

Thanks for the report!

PS: there's also a bug where the metrics in a new template or scout don't show up unless you close the screen and come back—I'm working on that too.

**Comment by blake1029384756** [comment]
Guess I should have read the log closer 😂. I do not need it for an event, I was just messing around.

**Comment by SUPERCILEX** [comment]
@blake1029384756 Haha, no problem. 😆 I know things are a little crazy right now, but since I just finished the database upgrade hopefully everything will return to sanity in a week or so.

Gonna keep this issue open even though I have to TODO in code so that I can have the satisfaction of closing it when I fix the spinner stuff. 🤣
