### ISSUE TITLE
Breakdown Power Rating (BPR)

### ISSUE THREAD

**Issue by blake1029384756** [SUPERCILEX/Robot-Scouter#178]
This new Stat for FRC is going to be very useful. It is open source and I was wondering if you could implement it. 
https://www.reddit.com/r/FRC/comments/7hrtnr/breakdown_power_rating_bpr_a_new_power_metric/

**Comment by SUPERCILEX** [comment]
Looks cool! However, I'm not sure how it could apply to Robot Scouter:
> BPR is an entirely objective statistic calculated **using data reported by the FMS** and the same math as familiar stats like OPR, DPR, and CCWM. **There are no human scouters**, no subjectivity, and most importantly no delay in reporting BPRs, making it an essential tool for strategy during competition.

BPR seems to come straight from the FMS' data... were you thinking of having the BPR calculated from a team's data vs. the FMS' reported data? If so, 😢. Robot Scouter's biggest limitation is that I have no idea what the data a team is collecting actually means. Since the scouts are customizable, it's all just random numbers as far as I'm concerned. That's why I try to export a really nice spreadsheet—so you can do all that fancy analysis knowing what your data means.

**Comment by blake1029384756** [comment]
I was thinking you could you the FMS data through the library that guy made. No need to have RS perform the calculations just import the results into the spreadsheet

**Comment by SUPERCILEX** [comment]
Oh I see! Yeah, good idea, I'll look into it.

**Comment by SUPERCILEX** [comment]
Ok, I've looked into the API and it seems to require a TAB match key. Since that will be supported with Auto Scout, I've moved this issue to #55 (my full spec is still in a private GDoc so you won't see this issue mentioned anywhere 😄).
