### ISSUE TITLE
Scout templates not loading when Wifi is off

### ISSUE THREAD

**Issue by 302scouting** [SUPERCILEX/Robot-Scouter#179]
### Step 1: Describe your environment
10 Kindles. All signing into Robot Scooter with the same gmail account.
 - Robot Scouter version: 2.0.0.5687
- Android OS version: 22
- User id: TqIcDU3KvjgZedtvrw6QdADzwTv1

### Step 2: Describe the problem:
Scout templates successfully show in template editor on each Kindle, by when Wifi is turned off a new "scout" will only add as a blank sheet labeled "Scout 1, Scout 2, etc" on some of the Kindles (See attached screenshots showing this issue using both our FRC and FTC templates). Does not happen to all Kindles at the same time and not always on the same one. This was an issue we noticed prior to the update and just realized is still happening post update. Thanks for your help!
![screenshot_2017-12-06-10-32-05](https://user-images.githubusercontent.com/31874931/33669660-13b24fe2-da71-11e7-8d45-9dab92239145.png)
![screenshot_2017-12-06-10-32-13](https://user-images.githubusercontent.com/31874931/33669667-1878de2e-da71-11e7-93f6-e9d438842e43.png)
![screenshot_2017-12-06-10-32-26](https://user-images.githubusercontent.com/31874931/33669676-1fa83938-da71-11e7-8c6a-09929759da69.png)

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

**Comment by SUPERCILEX** [comment]
@302scouting Could you try opening the Scout Template Editor (once with wifi) and tapping each tab on the devices where you're seeing that issue?

**Comment by SUPERCILEX** [comment]
Oh, yep that's the issue:
![image](https://user-images.githubusercontent.com/9490724/33673567-f97a6178-da61-11e7-8fde-693a53cdb941.png)

Here's what's going on: when you create a template on one device, it gets uploaded to the cloud. Then, when you create a new scout, the template is downloaded and stored on the device for offline use. However, if a device doesn't first load the template while online, we can't create a scout because the template hasn't been cached for offline use. Sadly, I can't think of a good solution to fix this—it just comes down to either loading the template through the Scout Template Editor or through creating a dummy scout to ensure it's cached.

@302scouting Do you have any ideas on how I could share this information? I definitely need an error message instead of a blank scout, but it's kinda too late by then. I'd really hate to see this happen for a team at an official competition.

**Comment by 302scouting** [comment]
Hmmm...let me give that some thought and I'll get back with you. Along that
line of thinking, is there a way to load a template into the app manually
(i.e. transfered to the Kindle via USB, then into Robot Scouter)?

On Dec 6, 2017 11:54 AM, "Alex Saveau" <notifications@github.com> wrote:

Oh, yep that's the issue:
[image: image]
<https://user-images.githubusercontent.com/9490724/33673567-f97a6178-da61-11e7-8fde-693a53cdb941.png>

Here's what's going on: when you create a template on one device, it gets
uploaded to the cloud. Then, when you create a new scout, the template is
downloaded and stored on the device for offline use. However, if a device
doesn't first load the template while online, we can't create a scout
because the template hasn't been cached for offline use. Sadly, I can't
think of a good solution to fix this—it just comes down to either loading
the template through the Scout Template Editor or through creating a dummy
scout to ensure it's cached.

@302scouting <https://github.com/302scouting> Do you have any ideas on how
I could share this information? I definitely need an error message instead
of a blank scout, but it's kinda too late by then. I'd really hate to see
this happen for a team at an official competition.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SUPERCILEX/Robot-Scouter/issues/179#issuecomment-349703239>,
or mute the thread

**Comment by SUPERCILEX** [comment]
Sadly nope. The only solution so far is to spend a few moments loading templates on the devices you're going to use pre-competition while you still have WiFi access. Sorry!

**Comment by SUPERCILEX** [comment]
I just got an idea to fix the problem: I'll add a fix to the [Auto Scout feature](https://github.com/SUPERCILEX/Robot-Scouter/issues/55). Since that feature will include a complete and guided flow to add all the teams going to a competition and do any setup necessary, I'll include a "cache required templates" section during the device pair.

In the meantime, I've clarified the error in 6e41d9a9e910d2bfc43ad0476b910ba60d0fdc6d so I'll be closing this issue. Feel free to reach out if there's anything else you need. 😀
