### ISSUE TITLE
Not really an issue, just a question on a widget

### ISSUE THREAD

**Issue by shilewen** [SUPERCILEX/Robot-Scouter#180]
What is the widget that you use for the # of bunnies count? It's where you can press up and down arrows to increment the number. Thanks

**Comment by SUPERCILEX** [comment]
@shilewen No problem! It's called the "Counter." Are you trying to find it for the scout template editor? If so, it should have an icon with numbers next to it. Let me know if there's anything else you'd like to know. 😄

**Comment by shilewen** [comment]
Oh I meant like the widget name of it in android studio code. Is it just a TextView with two Buttons? Or is it a downloadable widget? Btw thanks for responding

**Comment by SUPERCILEX** [comment]
Oh, I get it, trying to steal my ideas, eh? 😆 Nah, just kidding.

The widget is actually a little bit more complex than your average Joe since it includes both an XML and runtime component. You can find the base layout for the counter [here](https://github.com/SUPERCILEX/Robot-Scouter/blob/b1b369a62d93dbf2c21d252a51849e643f3363bb/app/src/main/res/layout/scout_base_counter.xml) and then the [scout](https://github.com/SUPERCILEX/Robot-Scouter/blob/b1b369a62d93dbf2c21d252a51849e643f3363bb/app/src/main/res/layout/scout_counter.xml) and [template](https://github.com/SUPERCILEX/Robot-Scouter/blob/b1b369a62d93dbf2c21d252a51849e643f3363bb/app/src/main/res/layout/scout_template_counter.xml) implementations. As for the [runtime component](https://github.com/SUPERCILEX/Robot-Scouter/blob/b1b369a62d93dbf2c21d252a51849e643f3363bb/app/src/main/java/com/supercilex/robotscouter/util/ui/CardListHelper.kt), it's in charge of setting the correct corners for the grouped "bubble" effect when using headers. At some point, I'd like to create my own custom `ViewGroup` which draws corners directly on the canvas, but that's a project for later.

I'm going to close this issue since I believe I've answered your questions, but if not, feel free to ask some more. 😉
