### ISSUE TITLE
Exported Excel file only showing stopwatch average, not all stopwatch cycles

### ISSUE THREAD

**Issue by 302scouting** [SUPERCILEX/Robot-Scouter#188]
### Step 1: Describe your environment

2.2.4.5751

### Step 2: Describe the problem:
When Robot Scouter exports the collected data, the resulting Excel file only shows the Stopwatch average as opposed to the individual cycle times. If only one field can show we would rather see the total time than the average time as one bad round can through off an average.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Expected Results:
I expected each individual cycle to show. We are more interested in the individual cycles than the average since one fluke round can throw off the average. If only one field can show we would rather have the total time than the average.

#### Other Relevant Bits:
[[2018_ALLIANCE_DATA] 773 - Kingsville CavalGears.xlsx](https://github.com/SUPERCILEX/Robot-Scouter/files/1734827/2018_ALLIANCE_DATA.773.-.Kingsville.CavalGears.xlsx)

**Comment by SUPERCILEX** [comment]
@302scouting if you click on the cell, you'll see that it's actually an inlined `AVERAGE` function with all the laps available:
![image](https://user-images.githubusercontent.com/9490724/36355815-f1e8ad72-149d-11e8-967c-5937e2bad87f.png)

I chose to use the average by default because that seemed like the choice that would convey the most actionable information. Now that I'm thinking about it, the median seems like a better function, what do you think? (I don't like the sum since that doesn't really tell you anything: more or less laps will radically change its value).

**Comment by 302scouting** [comment]
I think it would depend on what you are timing with the stopwatch. We, for
example, are planning to use the stopwatch feature in two ways: 1)In our
alliance scouting template to show how long the switch and scale have been
owned by that alliance and 2)In our individual robot scouter template to
show how long that robot has played defense. For these two ways, the total
would work best. However, there my be other ways we haven't thought of in
which the average or the median would be better.

On Feb 18, 2018 2:23 PM, "Alex Saveau" <notifications@github.com> wrote:

@302scouting <https://github.com/302scouting> if you click on the cell,
you'll see that it's actually an inlined AVERAGE function with all the laps
available:
[image: image]
<https://user-images.githubusercontent.com/9490724/36355815-f1e8ad72-149d-11e8-967c-5937e2bad87f.png>

I chose to use the average by default because that seemed like the choice
that would convey the most actionable information. Now that I'm thinking
about it, the median seems like a better function, what do you think? (I
don't like the sum since that doesn't really tell you anything: more or
less laps will radically change its value).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SUPERCILEX/Robot-Scouter/issues/188#issuecomment-366540286>,
or mute the thread

**Comment by 302scouting** [comment]
Followup thought...
If we cannot get the total and had to choose between average and median we
would choose average. With an average we could just add a field to the
template asking for total # of cycles. That way we would bw able to quickly
calculate the approximate total number. We would not be able to do this
with the median, however, and come as close to an accurate total. Thanks!

**Comment by SUPERCILEX** [comment]
@302scouting Ok, I've deliberated over this some more and have decided to leave it as is (average). Here's my reasoning:
- Some teams are still tracking cycle times for certain actions, so changing it to use `SUM` would break those teams.
- Given that year-independence is one of the core principles behind Robot Scouter, it can in theory be used for any game which makes me hesitant to make any changes that lean towards one year's game or another. However, if FIRST continues using time-based points in future years making this game the norm rather than the exception, I'll be happy to reconsider.

I wish I could give you a better answer, but any change I make will disappoint one party or another. 😞🤷‍♂️ Good luck! 😊

**Comment by 302scouting** [comment]
We can work with that! 😊
