### ISSUE TITLE
Huge lag on opening menu and when adding scouts

### ISSUE THREAD

**Issue by 302scouting** [SUPERCILEX/Robot-Scouter#201]
### Step 1: Describe your environment

- Robot Scouter version: 2.2.10.5808
- Android OS version: 26
- User id: TqIcDU3KvjgZedtvrw6QdADzwTv1

### Step 2: Describe the problem:
We are experiencing very significant lag/load times in Robot Scouter when opening the app (main menu screen not loading with saved data), when loading new scouts, and sometimes even when opening the template editing area. We are experiencing this issue both with wifi on and with wifi off. Sometimes the screen will just be empty/white and sometimes it will say its trying to connect with the cloud. We have tried exiting out of the app and going back in as well as shutting the kindle off and turning it back on. Sometimes we've had to resort to uninstalling/reinstalling the app. This evening, the only way to get the main menu list of teams to show on several of the kindles was to turn on night mode and wait for about 2 minutes. Your assistance in this matter is greatly appreciated.

**Comment by SUPERCILEX** [comment]
Huh, that's really weird since all of my devices are nice and snappy. I'll investigate tomorrow, but in the meantime, could you answer these questions:
- Is it just Robot Scouter being slow (or are other apps slow too)?
- Are any of the teams flashing constantly?
- Are your [play services](https://play.google.com/store/apps/details?id=com.google.android.gms) up-to-date?
- Does [clearing app data](https://www.cnet.com/how-to/how-to-clear-app-cache-and-app-data-in-android-6-0-marshmallow/) help?

Thanks in advance for working with me on this! 😊

PS: I'd recommend updating to the latest version of Robot Scouter since I broke spreadsheet exporting in the version you're on.

**Comment by 302scouting** [comment]
Hi Alex,

Here are the answers to your questions:


   - Is it just Robot Scouter being slow (or are other apps slow too)?
   --Just Robot Scouter
   - Are any of the teams flashing constantly? --Not sure what you mean by
   this.
   - Are your play services
   <https://play.google.com/store/apps/details?id=com.google.android.gms>
up-to-date?
   --Yes
   - Does clearing app data
   <https://www.cnet.com/how-to/how-to-clear-app-cache-and-app-data-in-android-6-0-marshmallow/>
help?
   I tried clearing the cache (see attached before/after pics), but there was
   still a blank screen delay for both the teams and the templates. It took
   3.5 min for them to show up.

Thanks,
Shannon

**Comment by SUPERCILEX** [comment]
Thanks! I see you deleted all your teams, but you'll want to add some back to keep testing this.

As for the teams flashing, don't worry about it since that won't be relevant when you add new ones.

For the clearing app data stuff, you'll want to actually clear app data instead of just the cache. That's more extreme than uninstalling since when you reinstall an app, some cached data is injected from Google Drive. You might have to sign back in if doesn't automatically, but I hope that's not too much of a bother. 😊

Please tell me how clearing app data goes!
