### ISSUE TITLE
App will not open

### ISSUE THREAD

**Issue by 302scouting** [SUPERCILEX/Robot-Scouter#237]
When trying to open app, just get a message that says "Robot Scouter has stopped." Tried uninstalling and reinstalling, but still had same issue.

**Comment by SUPERCILEX** [comment]
If you need a fix right now, please downgrade to beta or stable by [leaving the testing program](https://play.google.com/apps/testing/com.supercilex.robotscouter). Otherwise, I'll have a fix sometime this week or the next.

PS: It's caused by a third party dependency that will release the fix in a week or so.

**Comment by SUPERCILEX** [comment]
This is fixed in build 5856.
