### ISSUE TITLE
QR code or other direct export method

### ISSUE THREAD

**Issue by 302scouting** [SUPERCILEX/Robot-Scouter#239]
What is the possibility that Robot Scouter could have an option to export to a QR code or some other method of exporting info directly from the Robot Scouter app (see more detailed description in info below)? This could possibly allow teams to speed up the process of getting data from the scouting device (in our case, Kindles) to the primary analysis device (in our case, PC) without needing to utilize Bluetooth (which can be problematic) or flash drives.

We would like to get data to our analysis team more frequently and quickly. 
Here was our process this past season: Instead of "team" numbers we would enter a "batch" number into Robot Scouter. Each "batch" would contain 3 matches. At the completion of three matches, each scout would export that batch using the Robot Scouter export option and then "find" the exported file using the ES File Explorer app we loaded onto our scouting Kindles. Using the ES File Explorer app the scout would then copy/paste the exported file to a flash drive connected to the Kindle. All scouting flash drives were then taken to the Data Captain who would combine them into our Master Scouting Spreadsheet.
While this process worked, it was cumbersome and could definitely use improvement. We would like a way to be able to transfer data more frequently and efficiently possibly using QR codes or some other method that would enable us to transfer exported files/information directly from the Robot Scouter app rather than needing to use a 3rd part option such as ES File Manager.

**Comment by SUPERCILEX** [comment]
Yeah, I agree that this needs to be improved. To clarify, do you need this to work offline or can we assume an internet connection?

**Comment by 302scouting** [comment]
Hi Alex,

At competitions we work completely offline as the only allowable access to
wifi is in the pits.

Thanks!
Shannon

**Comment by andrewda** [comment]
A QR code can only hold 406 bytes (definitely not enough for any forms to be transferred). Maybe we could host a web server on the phone and allow connections over bluetooth, with a QR code sending the web server's address?

**Comment by SUPERCILEX** [comment]
I can't think of a good way to provide offline communication between an arbitrary device and Robot Scouter. 😢

However, [Auto Scout](https://github.com/SUPERCILEX/Robot-Scouter/issues/55) will support automatic exports which should speed things up. Also, I'm planning on making the [export folder customizable](https://github.com/SUPERCILEX/Robot-Scouter/issues/247) so you could export directly onto a USB in theory.

Hopefully those updates will speed things up enough!

**Comment by 302scouting** [comment]
Hi Alex,

exporting directly to a USB would be VERY helpful! When is Auto Scout due
to launch? When you said "automatic exports" did you mean that we could
leave a USB connected to the Kindle and it Robot Scouter would
automatically export each scout to the USB? Will it export every match,
every "x" matches, or every "x" minutes?

Thanks for all you do!
Shannon Cook
Scouting & Strategy Mentor, Team 302

**Comment by SUPERCILEX** [comment]
Auto Scout is the biggest project I've ever worked on for Robot Scouter, so it will happen in phases.

This year's phase is targeting setup for competition. So that's things like downloading teams for each competition, caching templates and other data so you never run into issues when devices are offline, helping users set up templates, etc.

Automatic exports are targeted for 2020. And your questions are exactly why this stuff is so hard. 😂 I'll have to figure how to get all the data offline, merge and deduplicate it, then understanding when it's a good time to export. I'm thinking after every match, but there's no infrastructure around that yet (Robot Scouter doesn't have a concept of matches). But to answer your question: yes, it would export directly to whatever folder you specify (be that on a USB or not).

Anyway, I hope you can see the complexity here and why this is taking so long. I really do wish I could find more free time to deliver! 😊
