### ISSUE TITLE
Add scouter leaderboard

### ISSUE THREAD

**Issue by andrewda** [SUPERCILEX/Robot-Scouter#248]
**Is your feature request related to a problem? Please describe.**

Some people aren't motivated to scout, so adding a team leaderboard would give some gamification incentive to get more people excited about scouting!

**Describe the solution you'd like**

A leaderboard tab in the bottom bar or page from the sidebar that will open a page with a list of all scouts, their team rank, and the number of times they've scouted (+ maybe the amount of time they've scouted for?)

**Describe alternatives you've considered**

Manually keeping a list or doing post-processing on the data after exporting to an Excel file. This is fine, but doesn't give live feedback, and manually keeping a list is difficult.

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

Or just give me an API 🙃 *cough* #194 	*cough*

**Comment by SUPERCILEX** [comment]
Lol, I know, I know, I'll create an API soon™. 😁 There was actually a CD discussion about gamifying scouting, so that will be part of Auto Scout. I added a link to this issue at the end of the [event cards section](https://github.com/SUPERCILEX/Robot-Scouter/issues/55#uix-cards-event). (`Ctrl + F` -> "A games card that lets scouters")

</br></br></br>

PS: can you get someone to send a PR to [update the default templates](https://github.com/SUPERCILEX/Robot-Scouter#updating-templates-%EF%B8%8F)?
