### ISSUE TITLE
Crash if offline and no templates are cached

### ISSUE THREAD

**Issue by SaarYogev** [SUPERCILEX/Robot-Scouter#273]
### Environment
Pixel 3a, using android Q. Robot Scouter version 738999.
### The problem:
While opening the app for the first time offline and trying to add a new scout, the app will crash.
#### Steps to reproduce:

1. Download the app, or delete it's data.
2.  Enter the app
3. Create a new team
4. Create a new scout
5. Creation fails, displaying a toast saying: 

> Error adding new scout: The template you are attempting to use hasn't been cached yet. Please add at least one scout while you have an internet connection so your template may be cached for offline use.
![Screenshot_20191130-182826](https://user-images.githubusercontent.com/10786057/69903736-300eda00-13a6-11ea-8126-cf595885fabc.png)

  a. From here it's a little inconsistent for me, sometimes it crashed immediately, while most times I had to do a bit more before it crashed, like go back then go to that team again, or try creating more scouts.

#### Observed Results:

1. App crashes
2. Going back to the app and trying to create more scouts won't help, app keeps crashing until it is given online access.

#### Expected Results:

Default templates will be downloaded in one of those occasions:
1.  When downloading the app
2. When first loading the app, during a setup loading screen.
3. When trying to create a new scout, just like now.

In my opinion the priority is 1>2>3. 1 occurs when the user has to have an online connection to download from the Play Store. 2 seems acceptable, as a first time setup kind of thing, and the user has nothing to do with a scoutless scouting app anyways.

If 2/3 are chosen, it should display a nice popup message, asking the user to go online to download required assets. It should not continue until the user goes online, as he has nothing else to do with the app.

**Comment by SUPERCILEX** [comment]
@SaarYogev Thanks for the report. This is expected behavior until [Auto Scout](https://github.com/SUPERCILEX/Robot-Scouter/issues/55#intro) comes along and solves this problem in a more elegant way.

The issue is that if you have a custom template, we have no way of knowing what it'll be without loading the team. That's not a huge issue in and of itself, but it means that (in theory) you could have a different custom template for every single team. Downloading all of those costs me money and is full of bugs if you edit the template in between now and competition. Auto Scout solves this problem by requiring you to pick the templates you'll use during the competition beforehand and then caching them on each device automatically.

**Comment by Rachel-6451** [comment]
Would you mind talking me oof this email list? I graduated last year and am
done with robotics.

Thanks and good luck!

**Comment by will-hou** [comment]
I think if you switch your notification status from "Watching" to "Not Watching" at the top of the site, you'll stop receiving emails for any new issues. 

Thanks for your interest in Robot Scouter, and best of luck in the future!

**Comment by SaarYogev** [comment]
@SUPERCILEX I didn't mean to download all templates, I suggested downloading the default templates only, when downloading the app from the *Play Store*.
Should cost you nothing and be a pretty small download, and the app can't be used without downloading the default templates anyways.
