### ISSUE TITLE
Season 2020

### ISSUE THREAD

**Issue by 7570Lucas** [SUPERCILEX/Robot-Scouter#284]
Hi!
My name is Lucas and I'm from team Newtech 7570 and I have a question. Will you be making version for the next (2020)season? 
Greetings from me!

**Comment by SUPERCILEX** [comment]
Yes and no. There's nothing to update app wise since the default templates are configurable server-side. If you'd like to contribute the 2020 templates, please do so! 😃 https://github.com/SUPERCILEX/Robot-Scouter/blob/ec9936b47676ebc469c5b4b011a059547b5308f2/app/server/functions/src/main/kotlin/com/supercilex/robotscouter/server/functions/Templates.kt

**Comment by will-hou** [comment]
Hey Lucas!

[SERT(Team 2521)](https://github.com/SouthEugeneRoboticsTeam)'s scouting team is planning on updating the default match and pit templates for the 2020 FRC game sometime in the next few weeks. 

But as @SUPERCILEX said, if your team wants to create your own custom templates as well (or modify the default ones a bit like we do), feel free to do so! Everything's wonderfully customizable. 

Thanks for checking out Robot Scouter! Please feel free to let us know if you have any questions.

Also if you're interested in seeing how our team uses Robot Scouter, you can read more about it [here](https://medium.com/southeugeneroboticsteam/using-robot-scouter-with-tableau-to-collect-and-analyze-scouting-data-d169ea4c6b15)

**Comment by SUPERCILEX** [comment]
Whoops

**Comment by SUPERCILEX** [comment]
The FIRST season was cancelled so I guess this isn't relevant anymore. https://www.firstinspires.org/covid-19
