### ISSUE TITLE
Can't sign in to app using GitHub

### ISSUE THREAD

**Issue by sudobeans** [SUPERCILEX/Robot-Scouter#286]
### Step 1: Describe your environment

- Robot Scouter version: 3.0.4.6130
- Android OS version: 25
- User id: O9clfr89GWS0G5PWiHJbUSjnt8y2

### Step 2: Describe the problem:
I clicked "Sign in with Google." It then put all my templates under my Google Account.
I realized that I didn't want to sign into my Google account on a device someone else will be using, so I went to the "link account" area, and clicked "Sign in with GitHub." I tried to sign in and it said "an unknown error occured." Signing  in using Google still works though.

Perhaps it would be nice if there was a "unlink account" option as well, or a "export templates" button.

#### Steps to reproduce:

  1. Log in using Google
  2. Click "link account" in the settings then "Github"
  3. Sign out
  4. Sign in using GitHub
  5. "An unknown error occured."

#### Observed Results:
"An unknown error occured" bubble at the bottom of my screen.

#### Expected Results:
I was hoping for "Great! Your account is linked" and to be able to sign in using GitHub.

#### Other Relevant Bits:
I'm using Google Chrome on my phone.
GitHub's settings say that Robot Scouter is an Authorized OAuth app.
Clicking "Revoke access" to Robot Scouter on my Google account didn't help.

I hope you can figure out something I can do to get GitHub sign up to work, or a way to migrate my templates to another account, because unfortunately the option didn't work. Thank you!

**Comment by SUPERCILEX** [comment]
Thanks for the incredibly detailed explanation! Sadly, I couldn't reproduce the bug so I can't fix the root cause of this issue, but I'm hoping it was a one-time error.

Anyway, to get you up and running again, I've sent you a password reset email. Once you create a new password, the Google and GitHub logins will be wiped. That way, you'll be able to set GitHub up again and it should work as expected. TBH though, we recommend using a team shared Google account for this kind of stuff.
