### ISSUE TITLE
Improve import feature

### ISSUE THREAD

**Issue by blake1029384756** [SUPERCILEX/Robot-Scouter#94]
* Robot Scouter version: 1.0.2.5276
* Android OS version: 23
* User id: wQPZykRqf9MmbHjgXuflEJ3q0G42

When I import data from a shared link it creates a double entry in the app if the team already exists. This makes the spreadsheet have two entries as well and is bad for analyzing data. 

Thank you for your work on this app. It's the best scouting app by far! 

![Imgur](http://i.imgur.com/Z5P3Pnq.jpg)

**Comment by SUPERCILEX** [comment]
@blake1029384756 I'm glad you like the scouting app! 😄 

As for the "bug," it's intentional. The two different 5801 and 2457 teams have different scouting templates meaning I would have no idea which one is using the right template if I tried to merge them. **If you want the two teams merged, you'll have to delete one of the scouting templates.**

You'll have to do the following for both teams if you want to keep one of the scouting templates:
1. Make sure you have an internet connection
1. Go to one of the teams -> "edit next scout template" in the menu options -> if it's the scout template you want to delete, tap reset for all teams. Otherwise, go to the other team and delete that template. _Note: if you don't really care about either scout template, just go through step 2 to delete the custom template for the other team as well and you're good to go! Otherwise, keep going._
1. Once you've reset the template, go to the other team and tap "edit next scout template". This ensures that the template you want to use is marked as active.
1. Go back to the team in which you deleted the template and tap on "edit next scout template". Here's where the magic should happen: either the team you opened or the other one will be deleted and its scouts will be merged into a single team.

Hope it worked out, cheers!

**Comment by blake1029384756** [comment]
Thanks for the help. I see why you did that now!
