### ISSUE TITLE
Formula error in the spreadsheet

### ISSUE THREAD

**Issue by blake1029384756** [SUPERCILEX/Robot-Scouter#96]
Any template that has an item selector doesn't get averaged correctly in the spreadsheet. It returns the error #NAME?

This is the formula:
=ARRAYFORMULA(INDEX(B6:C6, MATCH(MAX(COUNTIF(B6:C6, B6:C6)), COUNTIF(B6:C6, B6:C6), 0)))

![Imgur](http://i.imgur.com/9JdUFIJ.png)

**Comment by SUPERCILEX** [comment]
@blake1029384756 Oops! That was a lack of attention on my part. I don't have a copy of excel so I didn't bother to look up whether "ARRAYFORMULA" exists in excel. (Turns out it's a Google Sheets thing, not excel). Anyway, thanks for the bug report! 😄

PS: if you want your existing spreadsheets to calculate the average correctly, open them up in Google Sheets and it should work.
