### ISSUE TITLE
Force update is broken/ offline use?

### ISSUE THREAD

**Issue by blake1029384756** [SUPERCILEX/Robot-Scouter#99]
I updated to the new version that detects if we are on an old version. After I updated it still thinks im on an old version and wants me to update. 
Version=1.0.4.5292 
Edit: I opted out of the beta program and then reinstalled the app and the problem went away. so the problem occurs only with beta releases

secondly is it possible to store the data offline and then sync at a later time? This is very important because most venues dont have wifi.

**Comment by SUPERCILEX** [comment]
@blake1029384756 Yeah, I probably should have warned alpha users about this. I set the minimum app version to one that doesn't exist so that my automated tests can try breaking the app. (minimum was 6000, but 5292 is the latest which is why you couldn't remove the dialog). I'll update this post once I remove the minimum app version and you can join the beta program again.

@blake1029384756 What do you mean by store data offline? As in use the app offline? If so, then that's already set up! 😄 Try it, turn on airplane mode and play around with RS. There shouldn't be anything you can't do offline that you could do online. And yeah, once you go online again, everything will sync with the cloud.

**Comment by SUPERCILEX** [comment]
@blake1029384756 Yeah, I should have warned alpha channel people. I set the minimum version to `6000` which doesn't exist so that I could have my automated tests try breaking RS. I'll post a new comment when I set the minimum app version to `-1` again and you can join the beta program.

@blake1029384756 What do you mean by store data offline? As in use Robot Scouter offline? If so, that's already working! 😄 Try it, turn on airplane mode and play around with RS. Anything you can do while online should work exactly the same while offline.

**Comment by SUPERCILEX** [comment]
@blake1029384756 Alright, minimum version is back to `-1` so if you [join the beta](https://play.google.com/apps/testing/com.supercilex.robotscouter) and [clear app data](https://www.cnet.com/how-to/how-to-clear-app-cache-and-app-data-in-android-6-0-marshmallow/) you'll be good to go. 🚀

**Comment by blake1029384756** [comment]
Thanks so much! Yep offline works. Maybe add that feature to the Readme and the description in the store? Just so others don't get confused like I did.

**Comment by SUPERCILEX** [comment]
@blake1029384756 I didn't think about, thanks! (Fixed in 0f074f2)
